### ISSUE TITLE
support microdata

### ISSUE THREAD

**Issue by kajisha** [muryoimpl/buoys#25]
For SEO, I'd like to embed microdata in breadcrumb list.

See detail in below, plz:
https://schema.org/BreadcrumbList

**Comment by muryoimpl** [comment]
You can embed microdata in your generated template, but I think that microdata should be embeded in template as default, too. I'll add microdata to template next version :smile:

**Comment by muryoimpl** [comment]
@kajisha 
I've created [PR#27](https://github.com/muryoimpl/buoys/pull/27) about this issue.

**Comment by muryoimpl** [comment]
I merged PR#27 so I close this issue, Thank you for your review:exclamation:
